### ISSUE TITLE
mac上从剪贴板上传一直提示“failed: no image in clipboard or unsupported format”

### ISSUE THREAD

**Issue by goxofy** [pluveto/upgit#24]
但是实际剪贴板是有图片的

```
2022-02-21 16:41:51.043596 +0800 CST m=+0.000626072[INFO ] Started
2022-02-21 16:41:51.050874 +0800 CST m=+0.007904413[ERROR] abort: failed: no image in clipboard or unsupported format
goroutine 1 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.18.0-beta1/x64/src/runtime/debug/stack.go:24 +0x65
github.com/pluveto/upgit/lib/xlog.Verbose.Log({0xc0?, 0x63?, {0xc00001e198?, 0xc000079860?}, 0xc000127e40?}, {0x4323438, 0x8}, {0xc000016400?, 0x33?}, {0x0, ...})
	/Users/runner/work/upgit/upgit/lib/xlog/verbose.go:55 +0x12a
github.com/pluveto/upgit/lib/xlog.Verbose.Error(...)
	/Users/runner/work/upgit/upgit/lib/xlog/verbose.go:44
github.com/pluveto/upgit/lib/xlog.AbortErr({0x43ad4c0?, 0xc00004d0b0?})
	/Users/runner/work/upgit/upgit/lib/xlog/verbose.go:93 +0xf9
main.loadClipboard()
	/Users/runner/work/upgit/upgit/main.go:360 +0x231
main.mainCommand()
	/Users/runner/work/upgit/upgit/main.go:53 +0x85
main.main()
	/Users/runner/work/upgit/upgit/main.go:39 +0x7b
```

**Comment by pluveto** [comment]
截图来源，版本？

**Comment by goxofy** [comment]
截图通过Shottr
版本 v0.2.12

log如上

**Comment by pluveto** [comment]
看看有没有选项从而使用**位图格式**保存到剪贴板。如果是带透明通道或者其它什么格式，暂时不支持。

macOS 的截图是 https://github.com/golang-design/clipboard 基础库提供的，你也可以请求他们提供相关支持。

**Comment by goxofy** [comment]
明白了谢谢

**Comment by pluveto** [comment]
还有问题的话可以留言，否则可以关闭 issue
