### ISSUE TITLE
panic: clipboard: cannot use when CGO_ENABLED=0

### ISSUE THREAD

**Issue by emisjerry** [pluveto/upgit#25]
請問：是macOS需要做權限方面的設定嗎？應如何解決?

```
[18:36:32] jerry ➜ ~/Documents » upgit :clipboard -f markdown-simple
panic: clipboard: cannot use when CGO_ENABLED=0

goroutine 1 [running]:
golang.design/x/clipboard.initialize(...)
	/home/runner/go/pkg/mod/golang.design/x/clipboard@v0.6.0/clipboard_nocgo.go:9
golang.design/x/clipboard.Init(...)
	/home/runner/go/pkg/mod/golang.design/x/clipboard@v0.6.0/clipboard.go:102
main.loadClipboard(0x12c2fe0?)
	/home/runner/work/upgit/upgit/main.go:236 +0x66
main.main()
	/home/runner/work/upgit/upgit/main.go:99 +0x41b
[18:40:12] jerry ➜ ~/Documents »
```

**Comment by pluveto** [comment]
This issue should have been resolved. Please check if you have updated to the latest version

**Comment by emisjerry** [comment]
After upgraded to the latest release, upgit responsed another message:

```
[17:45:24] jerry ➜ ~/Documents » upgit table-editor-3.png -f markdown-simple
open /Users/jerry/bin/extensions: no such file or directory%
[17:45:37] jerry ➜ ~/Documents »
```

upgit had been copied to ~/bin.

**Comment by pluveto** [comment]
Note that for new version the config file layout is changed. And create `extensions` dir if required.

**Comment by emisjerry** [comment]
Thanks for your reply, i'll try again if i'm avaiable.
